

ALTER TABLE leagues
ADD COLUMN prestige INTEGER NOT NULL DEFAULT 50;

ALTER TABLE leagues
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;