ALTER TABLE players
ADD COLUMN finishing INTEGER NOT NULL DEFAULT 50,
ADD COLUMN shot_power INTEGER NOT NULL DEFAULT 50,
ADD COLUMN long_shots INTEGER NOT NULL DEFAULT 50,
ADD COLUMN positioning INTEGER NOT NULL DEFAULT 50,
ADD COLUMN heading INTEGER NOT NULL DEFAULT 50;

ALTER TABLE players
ADD COLUMN dribbling INTEGER NOT NULL DEFAULT 50,
ADD COLUMN ball_control INTEGER NOT NULL DEFAULT 50,
ADD COLUMN short_passing INTEGER NOT NULL DEFAULT 50,
ADD COLUMN long_passing INTEGER NOT NULL DEFAULT 50;


ALTER TABLE players
ADD COLUMN acceleration INTEGER NOT NULL DEFAULT 50,
ADD COLUMN sprint_speed INTEGER NOT NULL DEFAULT 50,
ADD COLUMN agility INTEGER NOT NULL DEFAULT 50;


ALTER TABLE players
ADD COLUMN marking INTEGER NOT NULL DEFAULT 50,
ADD COLUMN standing_tackle INTEGER NOT NULL DEFAULT 50,
ADD COLUMN sliding_tackle INTEGER NOT NULL DEFAULT 50;

ALTER TABLE players
ADD COLUMN stamina INTEGER NOT NULL DEFAULT 50,
ADD COLUMN strength INTEGER NOT NULL DEFAULT 50,
ADD COLUMN jumping INTEGER NOT NULL DEFAULT 50;

ALTER TABLE players
ADD COLUMN IF NOT EXISTS potential INTEGER NOT NULL DEFAULT 75;

